import PDFDocument from 'pdfkit'

export const generatePdf = async (data) => {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({
      size: 'A4',
      margins: { top: 40, bottom: 40, left: 40, right: 40 },
      bufferPages: true,
      info: {
        Author: 'ChaatGPT',
        Title: data.title,
        Creator: 'ChaatGPT',
      }
    });

    const chunks = []
    doc.on('data', (chunk) => chunks.push(chunk))
    doc.on('end', () => {
      const buffer = Buffer.concat(chunks)
      resolve(buffer)
    })
    doc.on('error', reject)

    // 1. TITLE
    doc.fillColor('#111827').fontSize(20).text(data.title, { align: 'center' })
    if (data.subtitle) doc.moveDown(0.5)

    // 2. SUBTITLE
    if (data.subtitle) {
      doc.fillColor('#6B7280').fontSize(14).text(data.subtitle, { align: 'center' })
      doc.moveDown(2)
    }

    // 3. SECTIONS
    data?.sections?.forEach((section, i) => {
      // Print Heading
      doc.fillColor('#111827').fontSize(16).text(`${i + 1}. ${section.heading}`, { align: 'left' })
      doc.moveDown(0.5)

      // Print Points
      section?.points?.forEach((point) => {
        doc.fillColor('#6B7280').fontSize(12).text(`- ${point}`, { align: 'left', lineGap: 4 })
        doc.moveDown(0.25)
      })

      doc.moveDown(1)
    })

    // FOOTER
    // const bottomPosition = doc.page.height - 50; 

    // doc.fillColor('#6B7280')
    //    .fontSize(10)
    //    .text('Generated by ChaatGPT', 50, bottomPosition, {
    //      align: 'center',
    //      // Define width so 'center' alignment knows the boundaries of the page
    //      width: doc.page.width - 100, 
    //      lineBreak: false
    //    })

    doc.end()
  })
}