import pptxgen from "pptxgenjs";

const colors = {
  primary: '2563EB', // Blue
  secondary: '0F172A', // Dark Slate
  text: '334155', 
  light: 'E2E8F0', 
  border: 'CBD5E1',
  white: 'FFFFFF', 
  muted: '64748B'
};

const addCover = (ppt, data) => {
  let slide = ppt.addSlide();
  slide.background = { color: colors.white };

  // Modern vertical accent bar on the left
  slide.addShape(ppt.ShapeType.rect, { 
    x: 0, y: 0, w: 0.3, h: '100%', 
    fill: { color: colors.primary } 
  });

  // Main Title
  slide.addText(data.title || "Presentation Title", {
    x: 1.0, y: 2.5, w: '85%', h: 1.5,
    fontSize: 48, 
    bold: true, 
    color: colors.secondary,
    fontFace: 'Aptos'
  });

  // Subtitle / Author
  slide.addText(data.subtitle || "A Modern Presentation", {
    x: 1.0, y: 4.2, w: '85%', h: 0.5,
    fontSize: 24, 
    color: colors.muted,
    fontFace: 'Aptos'
  });

  slide.addText(`Generated by SOENCHAT`, {
    x: 1.0, y: 6.5, w: '85%', h: 0.5,
    fontSize: 10, align: 'center', 
    color: colors.light, fontFace: 'Aptos'
  })
};

const addContentSlide = (ppt, title, points, index, totalSlides) => {
  let slide = ppt.addSlide();
  slide.background = { color: colors.white };

  // Slide Title
  slide.addText(title, {
    x: 0.5, y: 0.4, w: '90%', h: 0.6,
    fontSize: 32, 
    bold: true, 
    color: colors.secondary,
    fontFace: 'Aptos'
  });

  // Sleek horizontal separator line under the title
  slide.addShape(ppt.ShapeType.rect, { 
    x: 0.5, y: 1.1, w: 12.33, h: 0.03, // 12.33 width fits the LAYOUT_WIDE margins beautifully
    fill: { color: colors.border } 
  });

  // Content (Bullet Points)
  if (points && points.length > 0) {
    const formattedPoints = points.map(point => ({
      text: point,
      options: { 
        bullet: { color: colors.primary }, // Colored bullets for a premium feel
        color: colors.text, 
        fontSize: 22, 
        fontFace: 'Aptos', 
        breakLine: true, 
        paraSpaceAfter: 20 
      }
    }));

    slide.addText(formattedPoints, {
      x: 0.5, y: 1.5, w: '90%', h: 5.2,
      valign: 'top'
    });
  }

  // Footer: Slide Pagination
  slide.addText(`${index} / ${totalSlides}`, {
    x: 11.5, y: 6.8, w: 1.5, h: 0.4,
    fontSize: 12, 
    color: colors.muted, 
    align: 'right',
    fontFace: 'Aptos'
  });
};

const addThankYou = (ppt) => {
  let slide = ppt.addSlide();
  
  // Dark background for high-contrast impact at the end
  slide.background = { color: colors.secondary };

  // Large centered text
  slide.addText("Thank You", {
    x: '10%', y: '35%', w: '80%', h: 1.5,
    align: 'center', 
    fontSize: 56, 
    bold: true, 
    color: colors.white,
    fontFace: 'Aptos'
  });

  // Colored subtext
  slide.addText("Any Questions?", {
    x: '10%', y: '50%', w: '80%', h: 1.0,
    align: 'center', 
    fontSize: 28, 
    color: colors.primary,
    fontFace: 'Aptos'
  });

  slide.addText('Generated by SOENCHAT', {
    x: 1.0, y: 6.5, w: '85%', h: 0.5,
    fontSize: 10, align: 'center', 
    color: colors.light, fontFace: 'Aptos'
  })
};

export const generatePpt = async (data) => {
  let ppt = new pptxgen();
  ppt.layout = 'LAYOUT_WIDE'; // 16:9 Aspect Ratio (13.33 x 7.5 inches)
  ppt.author = 'SOENCHAT';
  ppt.title = data.title;
  ppt.subject = data.subtitle;
  ppt.company = 'SOENCHAT';
  ppt.lang = 'en-US';
  ppt.theme = {
    headFontFace: 'Aptos',
    bodyFontFace: 'Aptos',
  };

  addCover(ppt, data);

  data?.slides?.forEach((slide, i) => {
    addContentSlide(ppt, slide.title, slide.points, i + 1, data.slides.length);
  });

  addThankYou(ppt);
  return ppt;
};